version: "3.9"
services:
  redis:
    image: redis:7.2.3
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 6379
    ports:
      - 6379:6379
  api:
    build: .
    container_name: node_app
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - .:/home/projects
    links:
      - redis
    command: /bin/sh -c "nodemon index.js"
    ports:
      - 8000:8000
    # depends_on:
    #   - redis

